sns:
  label: 社交资料
  items:
    github:
      name: github
      label: Github
      type: text
      placeholder: '只需填入 Github 用户名即可'
    twitch:
      name: twitch
      label: twitch
      type: text
      placeholder: '只需填入 twitch 用户名即可'
    spotify:
      name: spotify
      label: spotify
      type: text
      placeholder: '只需填入 spotify 用户名即可'
    email:
      name: email
      label: 邮箱
      type: text
      placeholder: ''
    indexCategory:
      name: category
      label: 分类
      type: text
      placeholder: '首页展示分类'
    sign:
      name: sign
      label: 签名
      type: textarea
      placeholder: ''